Eloctra/Models/Product.cs
using Eloctra.Data;
using Eloctra.Data.Base;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Eloctra.Models
{
    public class Product:IEntityBase
    {
        [Key]
        public int Id { get; set; }

        public string Name { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
        public string ImageURL { get; set; }

        // defined category in data folder
        public Category Category { get; set; }

        // Relationships
        public int CompanyId { get; set; }
        [ForeignKey("CompanyId")]
        public Company Company { get; set; }
    }
}

Eloctra/Controllers/CompanyController.cs
using Eloctra.Data;
using Eloctra.Data.Services;
using Eloctra.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Eloctra.Controllers
{
    public class CompanyController : Controller
    {
        private readonly ICompanyService _service;

        public CompanyController(ICompanyService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAllAsync();
            return View(data);
        }

        //Get: Company/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Name,Logo,Description")] Company company)
        {
            if (!ModelState.IsValid)
            {
                return View(company);
            }
            await _service.AddAsync(company);
            return RedirectToAction(nameof(Index));
        }

        //Get: Company/Details/1
        public async Task<IActionResult> Details(int id)
        {
            var companyDetails = await _service.GetByIdAsync(id);

            if (companyDetails == null) return View("NotFound");
            return View(companyDetails);
        }

        //Get: Company/Edit//1
        public async Task<IActionResult> Edit(int id)
        {
            var companyDetails = await _service.GetByIdAsync(id);

            if (companyDetails == null) return View("NotFound");
            return View(companyDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id,[Bind("Id,Name,Logo,Description")] Company company)
        {
            if (!ModelState.IsValid)
            {
                return View(company);
            }
            await _service.UpdateAsync(id, company);
            return RedirectToAction(nameof(Index));
        }

        //Get: Company/Delete//1
        public async Task<IActionResult> Delete(int id)
        {
            var companyDetails = await _service.GetByIdAsync(id);

            if (companyDetails == null) return View("NotFound");
            return View(companyDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var companyDetails = await _service.GetByIdAsync(id);
            if (companyDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

    }
}

Eloctra/Controllers/OrdersController.cs
using Eloctra.Data.Cart;
using Eloctra.Data.Services;
using Eloctra.Data.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Eloctra.Controllers
{
    public class OrdersController : Controller
    {
        private readonly IProductService _productService;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrdersService _ordersService;
        public OrdersController(IProductService productService, ShoppingCart shoppingCart, IOrdersService ordersService)
        {
            _productService = productService;
            _shoppingCart = shoppingCart;
            _ordersService = ordersService;
        }

        public async Task<IActionResult> Index()
        {
            string userId = "";

            var orders = await _ordersService.GetOrdersByUserIdAsync(userId);
            return View(orders);
        }

        public IActionResult ShoppingCart()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var response = new ShoppingCartVM()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };

            return View(response);
        }

        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            var item = await _productService.GetProductByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.AddItemToCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _productService.GetProductByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            string userId = "";
            string userEmailAddress = "";

            await _ordersService.StoreOrderAsync(items, userId, userEmailAddress);
            await _shoppingCart.ClearShoppingCartAsync();

            return View("OrderCompleted");
        }
    }
}

Eloctra/Controllers/ProductController.cs
using Eloctra.Data;
using Eloctra.Data.Services;
using Eloctra.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Eloctra.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _service;

        public ProductController(IProductService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index()
        {
            var allProduct = await _service.GetAllAsync(n => n.Company);
            return View(allProduct);
        }

        //GET: Product/Details/1
        public async Task<IActionResult> Details(int id)
        {
            var ProductsDetail = await _service.GetProductByIdAsync(id);
            if (ProductsDetail == null) return View("NotFound");
            return View(ProductsDetail);
        }

        //GET: Product/Create
        public async Task<IActionResult> Create()
        {
            var productDropdownsData = await _service.GetNewProductDropdownsValues();

            ViewBag.Companies = new SelectList(productDropdownsData.Companies, "Id", "Name");
            

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(NewProductVM product)
        {
            if (!ModelState.IsValid)
            {
                var productDropdownsData = await _service.GetNewProductDropdownsValues();

                ViewBag.Companies = new SelectList(productDropdownsData.Companies, "Id", "Name");

                return View(product);
            }

            await _service.AddNewProductAsync(product);
            return RedirectToAction(nameof(Index));
        }


        //Get: Company/Edit//1
        public async Task<IActionResult> Edit(int id)
        {
            var productDetails = await _service.GetProductByIdAsync(id);
            if (productDetails == null) return View("NotFound");

            var response = new NewProductVM()
            {
                Id = productDetails.Id,
                Name = productDetails.Name,
                Description = productDetails.Description,
                Price = productDetails.Price,
                ImageURL = productDetails.ImageURL,
                Category = productDetails.Category,
                CompanyId = productDetails.CompanyId
            };

            var productDropdownsData = await _service.GetNewProductDropdownsValues();
            ViewBag.Companies = new SelectList(productDropdownsData.Companies, "Id", "Name");

            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, NewProductVM product)
        {
            if (id != product.Id) return View("NotFound");

            if (!ModelState.IsValid)
            {
                var productDropdownsData = await _service.GetNewProductDropdownsValues();
                ViewBag.Companies = new SelectList(productDropdownsData.Companies, "Id", "Name");

                return View(product);
            }

            await _service.UpdateProductAsync(product);
            return RedirectToAction(nameof(Index));
        }

        //Get: Company/Delete//1
        public async Task<IActionResult> Delete(int id)
        {
            var ProductDetails = await _service.GetByIdAsync(id);

            if (ProductDetails == null) return View("NotFound");
            return View(ProductDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ProductDetails = await _service.GetByIdAsync(id);
            if (ProductDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

    }
}

Eloctra/Views/Product/Create.cshtml
@model NewProductVM

@{
    ViewData["Title"] = "Create a new Product";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4>Create a new Product</h4>
        </p>

        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group text-center">
                                <img id="ImageURLPreview" />
                            </div>
                            <div class="form-group">
                                <label asp-for="Name" class="control-label"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Price" class="control-label"></label>
                                <input asp-for="Price" type="number" class="form-control" />
                                <span asp-validation-for="Price" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ImageURL" class="control-label"></label>
                                <input asp-for="ImageURL" class="form-control" />
                                <span asp-validation-for="ImageURL" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Category" class="control-label"></label>
                                <select asp-for="Category" class="form-control" asp-items="Html.GetEnumSelectList<Category>()"></select>
                                <span asp-validation-for="Category" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="CompanyId" class="control-label"></label>
                                <select asp-for="CompanyId" class="form-control" asp-items="ViewBag.Companies"></select>
                                <span asp-validation-for="CompanyId" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label asp-for="Description" class="control-label"></label>
                                <textarea asp-for="Description" class="form-control"></textarea>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 offset-4 text-center">
                        <img width="100%" id="ImageUrlPreview" />
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show all</a>
                    </div>
                </form>

            </div>
        </div>

    </div>
</div>

@section Scripts{
    <script>
        $(document).ready(function () {
            var output = document.getElementById('ImageURLPreview');
            output.src = $("#ImageURL").val();
        })

        $("#ImageURL").on("change", function () {
            var output = document.getElementById('ImageURLPreview');
            output.src = $(this).val();
        })
    </script>
}

Eloctra/Views/Product/Delete.cshtml
@model Product

@{
    ViewData["Title"] = "Delete confirmation";
}


<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Delete confirmation for @Model.Name</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <div class="form-group text-center">
                    <img class="border-info rounded-circle" style="max-width: 150px" id="LogoPreview" />
                </div>
                <div class="form-group">
                    <label asp-for="ImageURL" class="control-label"></label>
                    <input asp-for="ImageURL" class="form-control" readonly />
                    <span asp-validation-for="ImageURL" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" readonly />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" readonly />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Price" class="control-label"></label>
                    <input asp-for="Price" type="number" class="form-control" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
                <div class="col-md-6">

                    <div class="form-group">
                        <label asp-for="Category" class="control-label"></label>
                        <select asp-for="Category" class="form-control"></select>
                        <span asp-validation-for="Category" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="CompanyId" class="control-label"></label>
                        <select asp-for="CompanyId" class="form-control"></select>
                        <span asp-validation-for="CompanyId" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group">
                    <form asp-action="Delete">
                        <input type="hidden" asp-for="Id" />
                        <input type="submit" value="Confirm" class="btn btn-danger float-right" />
                    </form>
                    <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>

        $(document).ready(function () {
            var output = document.getElementById('LogoPreview');
            output.src = $("#ImageURL").val();
        })

    </script>
}

Eloctra/Views/Product/Details.cshtml
@model Product
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor Accessor

@{
    ViewData["Title"] = "Product details";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <div class="card mb-12">
            <div class="row g-0">
                <div class="col-md-12">
                    <div class="card-header text-white bg-info">
                        <p class="card-text">
                            <h5 class="card-title">
                                @Model.Name
                            </h5>
                        </p>
                    </div>
                </div>
                <div class="col-md-4">
                    <img src="@Model.ImageURL" width="100%" alt="@Model.Name">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <p class="card-text">@Model.Description</p>
                        <p class="card-text">
                            <b>Company: </b>

                            @if (@Accessor.HttpContext.Session.GetString("UserName") == "jayshah2002")
                            {
                                <a asp-controller="Company" asp-action="Details" asp-route-id="@Model.CompanyId">
                                    @Model.Company.Name
                                </a>
                            }
                            else
                            { @Model.Company.Name}
                        </p>
                        <p class="card-text"><b>Category: </b>@Model.Category</p>
                        <p class="card-text"><b>Price: </b>@Model.Price.ToString("c")</p>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="card-footer">
                        <p class="card-text">
                            <a class="btn btn-outline-primary float-right" asp-action="Index">
                                Back to List
                            </a>
                            <a class="btn btn-success text-white" asp-controller="Orders" asp-action="AddItemToShoppingCart" asp-route-id="@Model.Id"><i class="bi bi-cart-plus"></i> Add to Cart </a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Eloctra/Views/Product/Edit.cshtml
@model NewProductVM

@{
    ViewData["Title"] = "Update a new Product";
}


<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Update a New Product</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-group text-center">
                        <img id="ImageURLPreview" />
                    </div>
                    <div class="form-group">
                        <label asp-for="ImageURL" class="control-label"></label>
                        <input asp-for="ImageURL" class="form-control" />
                        <span asp-validation-for="ImageURL" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <input asp-for="Description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Price" class="control-label"></label>
                        <input asp-for="Price" type="number" class="form-control" />
                        <span asp-validation-for="Price" class="text-danger"></span>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="Category" class="control-label"></label>
                            <select asp-for="Category" class="form-control" asp-items="Html.GetEnumSelectList<Category>()"></select>
                            <span asp-validation-for="Category" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="CompanyId" class="control-label"></label>
                            <select asp-for="CompanyId" class="form-control" asp-items="ViewBag.Companies"></select>
                            <span asp-validation-for="CompanyId" class="text-danger"></span>
                        </div>

                    </div>
                    <div class="form-group">
                        <input type="submit" value="Update" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>

        $(document).ready(function () {
            var output = document.getElementById('ImageURLPreview');
            output.src = $("#ImageURL").val();
        })

        $("#ImageURL").on("change", function () {
            var output = document.getElementById('ImageURLPreview');
            output.src = $(this).val();
        })
    </script>
}

Eloctra/Views/Product/Index.cshtml
@model IEnumerable<Product>
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor Accessor

@{
    ViewData["Title"] = "List of Products";
}


<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-4 col-xs-6 border-primary mb-3">
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header text-white bg-info">
                            <p class="card-text">
                                <h5 class="card-title">
                                    @item.Name &nbsp;&nbsp;&nbsp;
                                    @if (@Accessor.HttpContext.Session.GetString("UserName") == "jayshah2002")
                                    {
                                        <a class="btn btn-light" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                                    }
                                </h5>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <img src="@item.ImageURL" width="100%" alt="@item.Name">
                    </div>
                    <div class="col-md-6">
                        <div class="card-body">
                            <p class="card-text"><b>Company: </b>@item.Company.Name</p>
                            <p class="card-text"><b>Category: </b>@item.Category</p>
                            <p class="card-text"><b>Price: </b>@item.Price.ToString("c")</p>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="card-footer ">
                            <p class="card-text">
                                <a class="btn btn-outline-primary float-right" asp-action="Details" asp-route-id="@item.Id">
                                    <i class="bi bi-eye-fill"></i> Show Details
                                </a>
                                @if (@Accessor.HttpContext.Session.GetString("UserName") == null)
                                {
                                    <a class="btn btn-success text-white" asp-controller="account" asp-action="login" asp-route-id="@item.Id"><i class="bi bi-cart-plus"></i> Add to Cart </a>

                                }
                                else
                                {
                                    <a class="btn btn-success text-white" asp-controller="Orders" asp-action="AddItemToShoppingCart" asp-route-id="@item.Id"><i class="bi bi-cart-plus"></i> Add to Cart </a>
                                }
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>


@if (@Accessor.HttpContext.Session.GetString("UserName") == "jayshah2002")
{
    <div style="position: fixed; right: 25px; bottom: 25px;" class="text-white">
        <a asp-controller="Product" asp-action="Create" class="btn btn-success">
            <i class="bi bi-plus-circle"></i> Add New
        </a>
    </div>
}